datasource:
    password: rootdev

mybatis-plus:
  mapper-locations: classpath:/repository/*.xml
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    initialization-mode: always
    data: classpath:db/data.sql
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    platform: h2
    schema: classpath:db/schema.sql
    url: jdbc:h2:~/test
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql